pipeline {
    agent {
        docker {
            image 'amazon/aws-cli'
            args '-u root' // Use root user for AWS CLI
        }
    }
    environment {
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        AWS_DEFAULT_REGION = 'us-east-1' // Replace with your desired AWS region
    }
    stages {
        stage('Create S3 Bucket') {
            steps {
                script {
                    sh 'aws s3api create-bucket --bucket my-example-bucket-yv'
                }
            }
        }
    }
}
