pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                sshagent(credentials: ['ssh-key-for-jenkins']) {
                    checkout scm
                }
            }
        }

        // Add more pipeline stages as needed
    }
}
